<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="34167" started-at="2020-03-23T11:32:37 IST" finished-at="2020-03-23T11:33:11 IST">
    <groups>
    </groups>
    <test name="Test" duration-ms="34167" started-at="2020-03-23T11:32:37 IST" finished-at="2020-03-23T11:33:11 IST">
      <class name="testScripts.BookModuleTest">
        <test-method status="PASS" signature="AppLaunch()[pri:0, instance:testScripts.BookModuleTest@64bf3bbf]" name="AppLaunch" is-config="true" duration-ms="18301" started-at="2020-03-23T11:32:37 IST" finished-at="2020-03-23T11:32:55 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AppLaunch -->
        <test-method status="PASS" signature="TravelAgentInvalidLoginTest()[pri:0, instance:testScripts.BookModuleTest@64bf3bbf]" name="TravelAgentInvalidLoginTest" duration-ms="14974" started-at="2020-03-23T11:32:55 IST" finished-at="2020-03-23T11:33:10 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TravelAgentInvalidLoginTest -->
        <test-method status="FAIL" signature="TravelAgencyTitleTest()[pri:0, instance:testScripts.BookModuleTest@64bf3bbf]" name="TravelAgencyTitleTest" duration-ms="117" started-at="2020-03-23T11:33:10 IST" depends-on-methods="testScripts.BookModuleTest.TravelAgentInvalidLoginTest" finished-at="2020-03-23T11:33:11 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [TRAVEL AGENT SIGNIN] but found [TRAVEL AGENT LOGIN]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [TRAVEL AGENT SIGNIN] but found [TRAVEL AGENT LOGIN]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at testScripts.BookModuleTest.TravelAgencyTitleTest(BookModuleTest.java:53)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TravelAgencyTitleTest -->
        <test-method status="PASS" signature="TearDown()[pri:0, instance:testScripts.BookModuleTest@64bf3bbf]" name="TearDown" is-config="true" duration-ms="587" started-at="2020-03-23T11:33:11 IST" finished-at="2020-03-23T11:33:11 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TearDown -->
      </class> <!-- testScripts.BookModuleTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
